// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotation.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAnnotation = `-- name: CreateAnnotation :one
INSERT INTO annotations (id, image_id, type, coordinates, label_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, image_id, type, coordinates, label_id, created_at
`

type CreateAnnotationParams struct {
	ID          string
	ImageID     string
	Type        string
	Coordinates string
	LabelID     sql.NullString
}

func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, createAnnotation,
		arg.ID,
		arg.ImageID,
		arg.Type,
		arg.Coordinates,
		arg.LabelID,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.Type,
		&i.Coordinates,
		&i.LabelID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :exec
DELETE FROM annotations WHERE id = ?
`

func (q *Queries) DeleteAnnotation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotation, id)
	return err
}

const deleteAnnotationsByImage = `-- name: DeleteAnnotationsByImage :exec
DELETE FROM annotations WHERE image_id = ?
`

func (q *Queries) DeleteAnnotationsByImage(ctx context.Context, imageID string) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationsByImage, imageID)
	return err
}

const getAnnotation = `-- name: GetAnnotation :one
SELECT id, image_id, type, coordinates, label_id, created_at FROM annotations WHERE id = ?
`

func (q *Queries) GetAnnotation(ctx context.Context, id string) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, getAnnotation, id)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.Type,
		&i.Coordinates,
		&i.LabelID,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnotationsByImage = `-- name: ListAnnotationsByImage :many
SELECT id, image_id, type, coordinates, label_id, created_at FROM annotations WHERE image_id = ? ORDER BY created_at
`

func (q *Queries) ListAnnotationsByImage(ctx context.Context, imageID string) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotationsByImage, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.ImageID,
			&i.Type,
			&i.Coordinates,
			&i.LabelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnotation = `-- name: UpdateAnnotation :one
UPDATE annotations SET type = ?, coordinates = ?, label_id = ? WHERE id = ?
RETURNING id, image_id, type, coordinates, label_id, created_at
`

type UpdateAnnotationParams struct {
	Type        string
	Coordinates string
	LabelID     sql.NullString
	ID          string
}

func (q *Queries) UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, updateAnnotation,
		arg.Type,
		arg.Coordinates,
		arg.LabelID,
		arg.ID,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.Type,
		&i.Coordinates,
		&i.LabelID,
		&i.CreatedAt,
	)
	return i, err
}
