// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, image_id, annotation_id, author, body, type)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, image_id, annotation_id, author, body, type, resolved, created_at, updated_at
`

type CreateCommentParams struct {
	ID           string
	ImageID      string
	AnnotationID sql.NullString
	Author       string
	Body         string
	Type         string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ID,
		arg.ImageID,
		arg.AnnotationID,
		arg.Author,
		arg.Body,
		arg.Type,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.AnnotationID,
		&i.Author,
		&i.Body,
		&i.Type,
		&i.Resolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments
WHERE id = ? AND image_id = ?
`

type DeleteCommentParams struct {
	ID      string
	ImageID string
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.ImageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getComment = `-- name: GetComment :one
SELECT
    comments.id, comments.image_id, comments.annotation_id, comments.author, comments.body, comments.type, comments.resolved, comments.created_at, comments.updated_at,
    CASE
        WHEN comments.annotation_id IS NOT NULL AND annotations.id IS NULL THEN 1
        ELSE 0
    END AS target_deleted
FROM comments
LEFT JOIN annotations ON annotations.id = comments.annotation_id
WHERE comments.id = ? AND comments.image_id = ?
`

type GetCommentParams struct {
	ID      string
	ImageID string
}

type GetCommentRow struct {
	Comment       Comment
	TargetDeleted int64
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (GetCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getComment, arg.ID, arg.ImageID)
	var i GetCommentRow
	err := row.Scan(
		&i.Comment.ID,
		&i.Comment.ImageID,
		&i.Comment.AnnotationID,
		&i.Comment.Author,
		&i.Comment.Body,
		&i.Comment.Type,
		&i.Comment.Resolved,
		&i.Comment.CreatedAt,
		&i.Comment.UpdatedAt,
		&i.TargetDeleted,
	)
	return i, err
}

const listCommentsByImage = `-- name: ListCommentsByImage :many
SELECT
    comments.id, comments.image_id, comments.annotation_id, comments.author, comments.body, comments.type, comments.resolved, comments.created_at, comments.updated_at,
    CASE
        WHEN comments.annotation_id IS NOT NULL AND annotations.id IS NULL THEN 1
        ELSE 0
    END AS target_deleted
FROM comments
LEFT JOIN annotations ON annotations.id = comments.annotation_id
WHERE comments.image_id = ?
ORDER BY comments.created_at, comments.id
`

type ListCommentsByImageRow struct {
	Comment       Comment
	TargetDeleted int64
}

func (q *Queries) ListCommentsByImage(ctx context.Context, imageID string) ([]ListCommentsByImageRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByImage, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByImageRow
	for rows.Next() {
		var i ListCommentsByImageRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.ImageID,
			&i.Comment.AnnotationID,
			&i.Comment.Author,
			&i.Comment.Body,
			&i.Comment.Type,
			&i.Comment.Resolved,
			&i.Comment.CreatedAt,
			&i.Comment.UpdatedAt,
			&i.TargetDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentResolved = `-- name: SetCommentResolved :execrows
UPDATE comments
SET resolved = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND image_id = ?
`

type SetCommentResolvedParams struct {
	Resolved bool
	ID       string
	ImageID  string
}

func (q *Queries) SetCommentResolved(ctx context.Context, arg SetCommentResolvedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCommentResolved, arg.Resolved, arg.ID, arg.ImageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
