// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edge.sql

package sqlcgen

import (
	"context"
)

const createEdge = `-- name: CreateEdge :one
INSERT INTO edges (id, image_id, source_annotation_id, target_annotation_id, type)
VALUES (?, ?, ?, ?, ?)
RETURNING id, image_id, source_annotation_id, target_annotation_id, type
`

type CreateEdgeParams struct {
	ID                 string
	ImageID            string
	SourceAnnotationID string
	TargetAnnotationID string
	Type               string
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) (Edge, error) {
	row := q.db.QueryRowContext(ctx, createEdge,
		arg.ID,
		arg.ImageID,
		arg.SourceAnnotationID,
		arg.TargetAnnotationID,
		arg.Type,
	)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.SourceAnnotationID,
		&i.TargetAnnotationID,
		&i.Type,
	)
	return i, err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM edges WHERE id = ?
`

func (q *Queries) DeleteEdge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEdge, id)
	return err
}

const deleteEdgesByImage = `-- name: DeleteEdgesByImage :exec
DELETE FROM edges WHERE image_id = ?
`

func (q *Queries) DeleteEdgesByImage(ctx context.Context, imageID string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByImage, imageID)
	return err
}

const listEdgesByImage = `-- name: ListEdgesByImage :many
SELECT id, image_id, source_annotation_id, target_annotation_id, type FROM edges WHERE image_id = ? ORDER BY id
`

func (q *Queries) ListEdgesByImage(ctx context.Context, imageID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesByImage, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.ImageID,
			&i.SourceAnnotationID,
			&i.TargetAnnotationID,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
