// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guideline.sql

package sqlcgen

import (
	"context"
)

const createGuideline = `-- name: CreateGuideline :one
INSERT INTO guidelines (id, project_id, title, body, display_order)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, title, body, display_order, updated_at
`

type CreateGuidelineParams struct {
	ID           string
	ProjectID    string
	Title        string
	Body         string
	DisplayOrder int64
}

func (q *Queries) CreateGuideline(ctx context.Context, arg CreateGuidelineParams) (Guideline, error) {
	row := q.db.QueryRowContext(ctx, createGuideline,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Body,
		arg.DisplayOrder,
	)
	var i Guideline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.DisplayOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuideline = `-- name: DeleteGuideline :execrows
DELETE FROM guidelines
WHERE id = ? AND project_id = ?
`

type DeleteGuidelineParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteGuideline(ctx context.Context, arg DeleteGuidelineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGuideline, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGuideline = `-- name: GetGuideline :one
SELECT id, project_id, title, body, display_order, updated_at FROM guidelines
WHERE id = ? AND project_id = ?
`

type GetGuidelineParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetGuideline(ctx context.Context, arg GetGuidelineParams) (Guideline, error) {
	row := q.db.QueryRowContext(ctx, getGuideline, arg.ID, arg.ProjectID)
	var i Guideline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.DisplayOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuidelinesByProject = `-- name: ListGuidelinesByProject :many
SELECT id, project_id, title, body, display_order, updated_at FROM guidelines
WHERE project_id = ?
ORDER BY display_order, title, id
`

func (q *Queries) ListGuidelinesByProject(ctx context.Context, projectID string) ([]Guideline, error) {
	rows, err := q.db.QueryContext(ctx, listGuidelinesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guideline
	for rows.Next() {
		var i Guideline
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.DisplayOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuideline = `-- name: UpdateGuideline :one
UPDATE guidelines
SET title = ?,
    body = ?,
    display_order = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND project_id = ?
RETURNING id, project_id, title, body, display_order, updated_at
`

type UpdateGuidelineParams struct {
	Title        string
	Body         string
	DisplayOrder int64
	ID           string
	ProjectID    string
}

func (q *Queries) UpdateGuideline(ctx context.Context, arg UpdateGuidelineParams) (Guideline, error) {
	row := q.db.QueryRowContext(ctx, updateGuideline,
		arg.Title,
		arg.Body,
		arg.DisplayOrder,
		arg.ID,
		arg.ProjectID,
	)
	var i Guideline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.DisplayOrder,
		&i.UpdatedAt,
	)
	return i, err
}
