// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package sqlcgen

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v, status, uploaded_at, escalated
`

type CreateImageParams struct {
	ID             string
	ProjectID      string
	Filename       string
	OriginalWidth  int64
	OriginalHeight int64
	Width          int64
	Height         int64
	Rotation       int64
	FlipH          bool
	FlipV          bool
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.ID,
		arg.ProjectID,
		arg.Filename,
		arg.OriginalWidth,
		arg.OriginalHeight,
		arg.Width,
		arg.Height,
		arg.Rotation,
		arg.FlipH,
		arg.FlipV,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.Width,
		&i.Height,
		&i.Rotation,
		&i.FlipH,
		&i.FlipV,
		&i.Status,
		&i.UploadedAt,
		&i.Escalated,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v, status, uploaded_at, escalated FROM images WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.Width,
		&i.Height,
		&i.Rotation,
		&i.FlipH,
		&i.FlipV,
		&i.Status,
		&i.UploadedAt,
		&i.Escalated,
	)
	return i, err
}

const listImagesByProject = `-- name: ListImagesByProject :many
SELECT id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v, status, uploaded_at, escalated FROM images WHERE project_id = ? ORDER BY uploaded_at DESC
`

func (q *Queries) ListImagesByProject(ctx context.Context, projectID string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Filename,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.Width,
			&i.Height,
			&i.Rotation,
			&i.FlipH,
			&i.FlipV,
			&i.Status,
			&i.UploadedAt,
			&i.Escalated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByProjectAndStatus = `-- name: ListImagesByProjectAndStatus :many
SELECT id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v, status, uploaded_at, escalated FROM images WHERE project_id = ? AND status = ? ORDER BY uploaded_at DESC
`

type ListImagesByProjectAndStatusParams struct {
	ProjectID string
	Status    string
}

func (q *Queries) ListImagesByProjectAndStatus(ctx context.Context, arg ListImagesByProjectAndStatusParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByProjectAndStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Filename,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.Width,
			&i.Height,
			&i.Rotation,
			&i.FlipH,
			&i.FlipV,
			&i.Status,
			&i.UploadedAt,
			&i.Escalated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageTransform = `-- name: UpdateImageTransform :one
UPDATE images SET
    rotation = ?,
    flip_h = ?,
    flip_v = ?,
    width = ?,
    height = ?
WHERE id = ?
RETURNING id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v, status, uploaded_at, escalated
`

type UpdateImageTransformParams struct {
	Rotation int64
	FlipH    bool
	FlipV    bool
	Width    int64
	Height   int64
	ID       string
}

func (q *Queries) UpdateImageTransform(ctx context.Context, arg UpdateImageTransformParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, updateImageTransform,
		arg.Rotation,
		arg.FlipH,
		arg.FlipV,
		arg.Width,
		arg.Height,
		arg.ID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.Width,
		&i.Height,
		&i.Rotation,
		&i.FlipH,
		&i.FlipV,
		&i.Status,
		&i.UploadedAt,
		&i.Escalated,
	)
	return i, err
}

const updateImageWorkflow = `-- name: UpdateImageWorkflow :one
UPDATE images SET status = ?, escalated = ? WHERE id = ?
RETURNING id, project_id, filename, original_width, original_height, width, height, rotation, flip_h, flip_v, status, uploaded_at, escalated
`

type UpdateImageWorkflowParams struct {
	Status    string
	Escalated bool
	ID        string
}

func (q *Queries) UpdateImageWorkflow(ctx context.Context, arg UpdateImageWorkflowParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, updateImageWorkflow, arg.Status, arg.Escalated, arg.ID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.Width,
		&i.Height,
		&i.Rotation,
		&i.FlipH,
		&i.FlipV,
		&i.Status,
		&i.UploadedAt,
		&i.Escalated,
	)
	return i, err
}
