// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: label.sql

package sqlcgen

import (
	"context"
)

const createLabelDefinition = `-- name: CreateLabelDefinition :one
INSERT INTO label_definitions (id, project_id, name, color, category)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, name, color, category
`

type CreateLabelDefinitionParams struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
	Category  string
}

func (q *Queries) CreateLabelDefinition(ctx context.Context, arg CreateLabelDefinitionParams) (LabelDefinition, error) {
	row := q.db.QueryRowContext(ctx, createLabelDefinition,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.Category,
	)
	var i LabelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Category,
	)
	return i, err
}

const deleteLabelDefinition = `-- name: DeleteLabelDefinition :exec
DELETE FROM label_definitions WHERE id = ?
`

func (q *Queries) DeleteLabelDefinition(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLabelDefinition, id)
	return err
}

const getLabelDefinition = `-- name: GetLabelDefinition :one
SELECT id, project_id, name, color, category FROM label_definitions WHERE id = ?
`

func (q *Queries) GetLabelDefinition(ctx context.Context, id string) (LabelDefinition, error) {
	row := q.db.QueryRowContext(ctx, getLabelDefinition, id)
	var i LabelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Category,
	)
	return i, err
}

const listLabelDefinitions = `-- name: ListLabelDefinitions :many
SELECT id, project_id, name, color, category FROM label_definitions WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListLabelDefinitions(ctx context.Context, projectID string) ([]LabelDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listLabelDefinitions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabelDefinition
	for rows.Next() {
		var i LabelDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabelDefinition = `-- name: UpdateLabelDefinition :one
UPDATE label_definitions SET name = ?, color = ?, category = ? WHERE id = ?
RETURNING id, project_id, name, color, category
`

type UpdateLabelDefinitionParams struct {
	Name     string
	Color    string
	Category string
	ID       string
}

func (q *Queries) UpdateLabelDefinition(ctx context.Context, arg UpdateLabelDefinitionParams) (LabelDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateLabelDefinition,
		arg.Name,
		arg.Color,
		arg.Category,
		arg.ID,
	)
	var i LabelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Category,
	)
	return i, err
}
