// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Annotation struct {
	ID          string
	ImageID     string
	Type        string
	Coordinates string
	LabelID     sql.NullString
	CreatedAt   string
}

type Edge struct {
	ID                 string
	ImageID            string
	SourceAnnotationID string
	TargetAnnotationID string
	Type               string
}

type Image struct {
	ID             string
	ProjectID      string
	Filename       string
	OriginalWidth  int64
	OriginalHeight int64
	Width          int64
	Height         int64
	Rotation       int64
	FlipH          bool
	FlipV          bool
	Status         string
	UploadedAt     string
}

type LabelDefinition struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
	Category  string
}

type Project struct {
	ID        string
	Name      string
	CreatedAt string
}
