// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Annotation struct {
	ID          string
	ImageID     string
	Type        string
	Coordinates string
	LabelID     sql.NullString
	CreatedAt   string
}

type Comment struct {
	ID           string
	ImageID      string
	AnnotationID sql.NullString
	Author       string
	Body         string
	Type         string
	Resolved     bool
	CreatedAt    string
	UpdatedAt    string
}

type Edge struct {
	ID                 string
	ImageID            string
	SourceAnnotationID string
	TargetAnnotationID string
	Type               string
}

type Guideline struct {
	ID           string
	ProjectID    string
	Title        string
	Body         string
	DisplayOrder int64
	UpdatedAt    string
}

type Image struct {
	ID             string
	ProjectID      string
	Filename       string
	OriginalWidth  int64
	OriginalHeight int64
	Width          int64
	Height         int64
	Rotation       int64
	FlipH          bool
	FlipV          bool
	Status         string
	UploadedAt     string
	Escalated      bool
}

type LabelDefinition struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
	Category  string
}

type Project struct {
	ID        string
	Name      string
	CreatedAt string
}
